### ISSUE TITLE
TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by Veinify** [Androz2091/AtlantaBot#176]
**Please describe the problem you are having in as much detail as possible:**
TypeError: Cannot read property 'user' of undefined

**To Reproduce**
run command invitations

**Expected behavior**
A clear and concise description of what you expected to happen:
TypeError: Cannot read property 'user' of undefined
at invites.filter (/app/commands/General/invitations.js:31:88)
at Map.filter (/rbd/pnpm-volume/6e0a6c9d-8740-4d20-a155-1b8398a6109b/node_modules/.registry.npmjs.org/@discordjs/collection/0.1.5/node_modules/@discordjs/collection/dist/index.js:189:17)
at Invitations.run (/app/commands/General/invitations.js:31:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Further details:**
- atlanta version:4.6.4
- discord.js version: 12.0-dev
- Node.js version:10.15.3
- Operating system:

**Additional context**
Add any other context about the problem here:

**Comment by Veinify** [comment]
Oh and also i got an error from the reboot command
The bot says No command found for undefined!
And the console says TypeError: Cannot read property 'conf' of undefined
