### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Majoramari** [Androz2091/AtlantaBot#177]
**Please describe the problem you are having in as much detail as possible:**
it's working fine on my pc but on the host i get this error
**To Reproduce**
i'm using oxide.host to host it with mongodb external
**Expected behavior**
A clear and concise description of what you expected to happen:
[2020-03-27 19:28:40.173]: LOG Loading Event: guildMemberRemove
[2020-03-27 19:28:40.174]: LOG Loading Event: guildMemberUpdate
[2020-03-27 19:28:40.178]: LOG Loading Event: message
[2020-03-27 19:28:40.179]: LOG Loading Event: messageUpdate
[2020-03-27 19:28:40.180]: LOG Loading Event: ready
[2020-03-27 19:28:40.481]: LOG Connected to the Mongodb database.
[2020-03-27 19:28:45.230]: LOG Loading a total of 113 command(s).
[2020-03-27 19:28:45.235]: READY Hanhona#3302, ready to serve undefined users in undefined servers.
[2020-03-27 19:28:45.469]: LOG Docs updated!
[2020-03-27 19:30:08.036]: CMD MajorAmari (309626033680941056) ran command play
[2020-03-27 19:30:17.478]: CMD MajorAmari (309626033680941056) ran command play
[2020-03-27 19:32:09.795]: CMD MajorAmari (309626033680941056) ran command play
[2020-03-27 19:32:20.280]: CMD MajorAmari (309626033680941056) ran command play
[2020-03-27 19:32:28.464]: CMD MajorAmari (309626033680941056) ran command skip
[2020-03-27 19:32:45.038]: CMD MajorAmari (309626033680941056) ran command play
[2020-03-27 19:32:55.488]: CMD MajorAmari (309626033680941056) ran command skip
[2020-03-27 19:33:04.056]: CMD MajorAmari (309626033680941056) ran command stop
[2020-03-27 19:33:09.254]: CMD MajorAmari (309626033680941056) ran command play
[2020-03-27 19:33:22.935]: CMD MajorAmari (309626033680941056) ran command stop
[2020-03-27 19:33:29.230]: CMD MajorAmari (309626033680941056) ran command help
TypeError: client.guilds.get is not a function
at /home/container/helpers/functions.js:57:39
at new Promise (<anonymous>)
at Object.supportLink (/home/container/helpers/functions.js:56:16)
at Help.run (/home/container/commands/General/help.js:85:92)
at module.exports.run (/home/container/events/message.js:224:17)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-03-27 19:35:12.374]: CMD MajorAmari (309626033680941056) ran command profile
TypeError: client.guilds.filter is not a function
at Profile.run (/home/container/commands/Economy/profile.js:53:43)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-03-27 19:35:30.843]: CMD MajorAmari (309626033680941056) ran command help
TypeError: client.guilds.get is not a function
at /home/container/helpers/functions.js:57:39
at new Promise (<anonymous>)
at Object.supportLink (/home/container/helpers/functions.js:56:16)
at Help.run (/home/container/commands/General/help.js:85:92)
at module.exports.run (/home/container/events/message.js:224:17)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-03-27 19:35:44.931]: CMD MajorAmari (309626033680941056) ran command ascii
[2020-03-27 19:35:53.273]: CMD MajorAmari (309626033680941056) ran command announcement
[2020-03-27 19:35:58.022]: CMD MajorAmari (309626033680941056) ran command announcement
[2020-03-27 19:36:19.644]: CMD MajorAmari (309626033680941056) ran command minecraft
[2020-03-27 19:37:20.592]: CMD MajorAmari (309626033680941056) ran command fortniteshop
[2020-03-27 19:37:33.630]: CMD MajorAmari (309626033680941056) ran command setfortniteshop
[2020-03-27 19:37:53.989]: CMD MajorAmari (309626033680941056) ran command random
[2020-03-27 19:38:10.054]: CMD MajorAmari (309626033680941056) ran command stats
TypeError: client.guilds.get is not a function
at /home/container/helpers/functions.js:57:39
at new Promise (<anonymous>)
at Object.supportLink (/home/container/helpers/functions.js:56:16)
at Stats.run (/home/container/commands/General/stats.js:41:34)
at module.exports.run (/home/container/events/message.js:224:17)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
**Screenshots**
If applicable, add screenshots to help explain your problem:
![image](https://user-images.githubusercontent.com/33487552/77794176-163f8400-7074-11ea-9f91-8b424da62cfd.png)

**Further details:**
- atlanta version: latest update
- discord.js version: 12.0.2
- Node.js version: 12
- Operating system: https://oxide.host/

**Additional context**
Add any other context about the problem here:
i hope you help me and add broadcast feature to the bot

**Comment by Androz2091** [comment]
Try to downgrade Discord.js: `npm install discordjs/discord.js#fe7df708e44e0280dfaf0f8e457b154781bb5140`

**Comment by Majoramari** [comment]
> Try to downgrade Discord.js: `npm install discordjs/discord.js#fe7df708e44e0280dfaf0f8e457b154781bb5140`

working fine thanks♥
