### ISSUE TITLE
Backup Cannot read property 'filter' of undefined BUG

### ISSUE THREAD

**Issue by qutziscoding** [Androz2091/AtlantaBot#229]
**Please describe the problem you are having in as much detail as possible:**
When I use the backup command I get **"Cannot read property 'filter' of undefined"**. If I log it I get this error.
```py
TypeError: Cannot read property 'filter' of undefined
    at Object.<anonymous> (Z:\atlanta\node_modules\discord-backup\lib\master\create.js:79:18)
    at step (Z:\atlanta\node_modules\discord-backup\lib\master\create.js:33:23)
    at Object.next (Z:\atlanta\node_modules\discord-backup\lib\master\create.js:14:53)
    at Z:\atlanta\node_modules\node_modules\discord-backup\lib\master\create.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (Z:\atlanta\node_modules\discord-backup\lib\master\create.js:4:12)
    at Object.getRoles (Z:\atlanta\node_modules\discord-backup\lib\master\create.js:74:12)
    at Z:\atlanta\node_modules\discord-backup\lib\index.js:192:67
    at step (Z:\atlanta\node_modules\discord-backup\lib\index.js:33:23)
    at Object.next (Z:\atlanta\node_modules\discord-backup\lib\index.js:14:53)
    at fulfilled (Z:\atlanta\node_modules\discord-backup\lib\index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**To Reproduce**
1. run the backup command with the create arg

**Expected behavior**
A clear and concise description of what you expected to happen:
Backup the server I dont know as i have not got the command working

**Screenshots**
If applicable, add screenshots to help explain your problem:
![Discord_DWYjW86uHM](https://user-images.githubusercontent.com/67007273/87224713-6b7f7700-c37f-11ea-849b-d0bf2f6c8b14.png)

**Further details:**
- atlanta version: master branch
- discord.js version: https://github.com/discordjs/discord.js#fe7df708e44e0280dfaf0f8e457b154781bb5140 the one in the package.json file for Atlanta 
- Node.js version: v14.2.0
- Operating system: Windows 10

**Comment by Androz2091** [comment]
Fixed in v4.7.2
