### ISSUE TITLE
Getting SentryError: Invalid Dsn when running the bot

### ISSUE THREAD

**Issue by IYR3775** [Androz2091/AtlantaBot#259]
(note: all dependencies were installed correctly. sentryDSN in config.js was not provided)
Command prompt output:

C:\ppbotB1>node atlanta.js
C:\ppbotB1\node_modules\@sentry\utils\dist\dsn.js:40
            throw new error_1.SentryError(ERROR_MESSAGE);
            ^

SentryError: Invalid Dsn
    at new SentryError (C:\ppbotB1\node_modules\@sentry\utils\dist\error.js:9:28)
    at Dsn._fromString (C:\ppbotB1\node_modules\@sentry\utils\dist\dsn.js:40:19)
    at new Dsn (C:\ppbotB1\node_modules\@sentry\utils\dist\dsn.js:13:18)
    at NodeBackend._setupTransport (C:\ppbotB1\node_modules\@sentry\node\dist\backend.js:25:19)
    at NodeBackend.BaseBackend (C:\ppbotB1\node_modules\@sentry\core\dist\basebackend.js:15:32)
    at new NodeBackend (C:\ppbotB1\node_modules\@sentry\node\dist\backend.js:15:42)
    at NodeClient.BaseClient (C:\ppbotB1\node_modules\@sentry\core\dist\baseclient.js:50:25)
    at new NodeClient (C:\ppbotB1\node_modules\@sentry\node\dist\client.js:19:23)
    at Object.initAndBind (C:\ppbotB1\node_modules\@sentry\core\dist\sdk.js:16:18)
    at Object.init (C:\ppbotB1\node_modules\@sentry\node\dist\sdk.js:102:12)
    at Object.<anonymous> (C:\ppbotB1\atlanta.js:11:9)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

**Comment by Androz2091** [comment]
Hello,
If you don't have a Sentry DSN, __remove__ the field from the config, make it empty (`''`) or delete the property.
