### ISSUE TITLE
BUG Invalid DSN

### ISSUE THREAD

**Issue by GalackQSM** [Androz2091/AtlantaBot#265]
Erreur pendant le démarrage du bot

SentryError: Invalid Dsn
    at new SentryError (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\utils\dist\error.js:9:28)
    at Dsn._fromString (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\utils\dist\dsn.js:40:19)
    at new Dsn (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\utils\dist\dsn.js:13:18)
    at NodeBackend._setupTransport (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\node\dist\backend.js:25:19)
    at NodeBackend.BaseBackend (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\core\dist\basebackend.js:15:32)
    at new NodeBackend (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\node\dist\backend.js:15:42)
    at NodeClient.BaseClient (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\core\dist\baseclient.js:50:25)
    at new NodeClient (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\node\dist\client.js:19:23)
    at Object.initAndBind (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\core\dist\sdk.js:16:18)
    at Object.init (C:\Users\cynthia\Desktop\AtlantaBot-develop\node_modules\@sentry\node\dist\sdk.js:102:12)
    at Object.<anonymous> (C:\Users\cynthia\Desktop\AtlantaBot-develop\bot.js:11:9)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

**Comment by Androz2091** [comment]
Bonjour,
Supprimez simplement le champ `sentryDSN` du fichier `config.js`.
