### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by vPhap** [Androz2091/AtlantaBot#277]
**Please describe the problem you are having in as much detail as possible:**
command <prefix>work don't work

**Further details:**
- atlanta version: 4.7.1
- discord.js version: 12.2.0
- Node.js version: 12.18.3
- Operating system: Heroku docker

**Additional context**
Add any other context about the problem here:
2020-07-28T11:44:00.733175+00:00 app[worker.1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2020-07-28T11:44:00.733210+00:00 app[worker.1]: TypeError: Cannot read property 'name' of null
2020-07-28T11:44:00.733212+00:00 app[worker.1]:     at Work.run (/app/commands/Economy/work.js:71:54)
2020-07-28T11:44:00.733212+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2020-07-28T11:44:00.733212+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-28T11:44:00.733424+00:00 app[worker.1]: TypeError: Cannot read property 'name' of null
2020-07-28T11:44:00.733424+00:00 app[worker.1]:     at Work.run (/app/commands/Economy/work.js:71:54)
2020-07-28T11:44:00.733425+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2020-07-28T11:44:00.733425+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)

"a": ":a:",
"w": ":regional_indicator_w:",
"r": ":regional_indicator_r:",
"d": ":regional_indicator_d:"

**Comment by Androz2091** [comment]
Did you keep the same `emojis.json` file? And is your bot on the [emoji server](https://emojis.atlanta-bot.fr)?

**Comment by Androz2091** [comment]
@vPhap are you still experiencing the issue?

**Comment by Androz2091** [comment]
Closed due to inactivity.
