### ISSUE TITLE
Music does not work

### ISSUE THREAD

**Issue by Mistik** [Androz2091/AtlantaBot#309]
Using the latest master branch.

The sound of the music simply doesnt play.

**Comment by cooldude7407** [comment]
neither does mine

**Comment by Levminer** [comment]
You have to install ffmpeg.

**Comment by MistikSenpa** [comment]
> You have to install ffmpeg.

I installed it and music still doesnt work. Im using the master branch

Could you advise me how you installed it?

I used this
https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-18-04/

**Comment by Androz2091** [comment]
@MistikSenpa do you have any error in the terminal?

**Comment by MistikSenpa** [comment]
well now on the latest version when I try and run the bot I get this error

root@ns528099:~/AtlantaBot# node atlanta.js
/root/AtlantaBot/node_modules/discord-player/src/Player.js:608
        }, this.options.leaveOnEmptyCooldown ?? 0)
                                              ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/AtlantaBot/node_modules/discord-player/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/AtlantaBot/base/Atlanta.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
root@ns528099:~/AtlantaBot# node atlanta.js
/root/AtlantaBot/node_modules/discord-player/src/Player.js:608
        }, this.options.leaveOnEmptyCooldown ?? 0)

**Comment by Levminer** [comment]
@MistikSenpa install node 14 or up. But the music part in the new update dont work for me.

**Comment by MistikSenpa** [comment]
> @MistikSenpa install node 14 or up. But the music part in the new update dont work for me.

I can’t use node14 I can only use node 12. Any fix for node12?

**Comment by Androz2091** [comment]
It will be fixed

**Comment by Androz2091** [comment]
This has been fixed
