### ISSUE TITLE
discord-player bug

### ISSUE THREAD

**Issue by qRumi** [Androz2091/AtlantaBot#321]
**npm start**

```
/app/node_modules/discord-player/src/Player.js:608
        }, this.options.leaveOnEmptyCooldown ?? 0)
                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/discord-player/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/base/Atlanta.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)

```
Also check this: [link](https://github.com/Androz2091/discord-player/issues/100), Which has same bug

**Comment by Ferratzo** [comment]
Have you tried to update node to the current release? That worked for me.

**Comment by qRumi** [comment]
WOW, thanks for your help. xD
