### ISSUE TITLE
Bot isnt Working

### ISSUE THREAD

**Issue by Hel4gate** [Androz2091/AtlantaBot#322]
when i use config.js my bot isnt working I paste my token correctly I don't know why

**Comment by Androz2091** [comment]
Hello, what do you mean by `your bot is not working`?

**Comment by Hel4gate** [comment]
i include all the infomation on the bot but he is isn't working all of things starting correctly

**Comment by Hel4gate** [comment]
F:\Freelance\GS\BOT\GS>pm2 start atlanta.js
connect EPERM //./pipe/rpc.sock
[PM2] Spawning PM2 daemon with pm2_home=C:\Users\ASHERA\.pm2
events.js:282
      throw er; // Unhandled 'error' event
      ^

Error: connect EPERM //./pipe/rpc.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1136:16)
Emitted 'error' event on ReqSocket instance at:
    at Socket.<anonymous> (C:\Users\ASHERA\AppData\Roaming\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\sock.js:201:49)
    at Socket.emit (events.js:305:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'connect',
  address: '//./pipe/rpc.sock'
}

**Comment by Hel4gate** [comment]
3   │ atlanta        │ default     │ 4.8.0   │ fork    │ 5072     │ 0s     │ 23   │ online    │ 0%       │ 40.0mb   │ ASHERA   │ disabled

**Comment by Hel4gate** [comment]
but thing is my bot isnt wakeup all of the things I give correctly on config jason

**Comment by Androz2091** [comment]
Can you try to start your bot without pm2? Like `node atlanta.js`?

**Comment by Hel4gate** [comment]
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\Freelance\GS\BOT\GS\node_modules\discord-player\index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\Freelance\GS\BOT\GS\base\Atlanta.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)

**Comment by Hel4gate** [comment]
when i start node atlanta.js look like this

**Comment by Hel4gate** [comment]
now everything is fixed when i using admin mode on my vs code no errrrr getting found but thing is not isn't starting I don't know why my token also right

**Comment by Hel4gate** [comment]
id  │ name       │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ atlanta    │ default     │ 4.8.0   │ fork    │ 4260     │ 0      │ 47   │ stopped   │ 0%       │ 0b       │ ASHERA   │ disabled

**Comment by Hel4gate** [comment]
bot is isnt wakeup faster please fix this

**Comment by alexandrus21a** [comment]
I have to some problem, bot doesn't wake up
node atlanta.js
SentryError: Invalid Dsn
    at new SentryError (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\utils\dist\error.js:9:28)
    at Dsn._fromString (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\utils\dist\dsn.js:39:19)
    at new Dsn (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\utils\dist\dsn.js:13:18)
    at NodeBackend._setupTransport (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\node\dist\backend.js
:96:19)
    at NodeBackend.BaseBackend (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\core\dist\basebackend.js
:15:32)
    at new NodeBackend (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\node\dist\backend.js:15:42)
    at NodeClient.BaseClient (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\core\dist\baseclient.js:51
:25)
    at new NodeClient (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\node\dist\client.js:19:23)
    at Object.initAndBind (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\core\dist\sdk.js:16:18)
    at Object.init (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\@sentry\node\dist\sdk.js:103:12)
    at Object.<anonymous> (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\atlanta.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Looks like your Sentry DSN key is invalid. If you do not intend to use Sentry, please remove the key from the configurat
ion file.
[2020-11-08 00:42:45.448]: LOG Loading a total of 8 categories.
[2020-11-08 00:42:45.451]: LOG Loading Command: 8ball. �
[2020-11-08 00:42:45.455]: LOG Loading Command: ascii. �
[2020-11-08 00:42:45.456]: LOG Loading Command: choice. �
[2020-11-08 00:42:45.457]: LOG Loading Command: findwords. �
[2020-11-08 00:42:45.458]: LOG Loading Command: flip. �
[2020-11-08 00:42:45.459]: LOG Loading Command: fml. �
[2020-11-08 00:42:45.464]: LOG Loading Command: joke. �
[2020-11-08 00:42:45.465]: LOG Loading Command: lmg. �
[2020-11-08 00:42:45.470]: LOG Loading Command: lovecalc. �
[2020-11-08 00:42:45.471]: LOG Loading Command: number. �
[2020-11-08 00:42:45.472]: LOG Loading Command: achievements. �
[2020-11-08 00:42:45.473]: LOG Loading Command: birthdate. �
[2020-11-08 00:42:45.473]: LOG Loading Command: deposit. �
[2020-11-08 00:42:45.474]: LOG Loading Command: divorce. �
[2020-11-08 00:42:45.477]: LOG Loading Command: leaderboard. �
[2020-11-08 00:42:45.478]: LOG Loading Command: marry. �
[2020-11-08 00:42:45.479]: LOG Loading Command: money. �
[2020-11-08 00:42:45.479]: LOG Loading Command: pay. �
[2020-11-08 00:42:45.480]: LOG Loading Command: profile. �
[2020-11-08 00:42:45.481]: LOG Loading Command: rep. �
[2020-11-08 00:42:45.482]: LOG Loading Command: rob. �
[2020-11-08 00:42:45.483]: LOG Loading Command: setbio. �
[2020-11-08 00:42:45.483]: LOG Loading Command: slots. �
[2020-11-08 00:42:45.484]: LOG Loading Command: withdraw. �
[2020-11-08 00:42:45.485]: LOG Loading Command: work. �
[2020-11-08 00:42:45.486]: LOG Loading Command: addcommand. �
[2020-11-08 00:42:45.487]: LOG Loading Command: addemoji. �
[2020-11-08 00:42:45.488]: LOG Loading Command: automod. �
[2020-11-08 00:42:45.489]: LOG Loading Command: autorole. �
[2020-11-08 00:42:45.498]: LOG Loading Command: backup. �
[2020-11-08 00:42:45.500]: LOG Loading Command: configuration. �
[2020-11-08 00:42:45.500]: LOG Loading Command: delcommand. �
[2020-11-08 00:42:45.501]: LOG Loading Command: deletemod. �
[2020-11-08 00:42:45.502]: LOG Loading Command: goodbye. �
[2020-11-08 00:42:45.502]: LOG Loading Command: ignore. �
[2020-11-08 00:42:45.505]: ERROR Unable to load command setfortniteshop.js: Error: Could not parse font file
[2020-11-08 00:42:45.506]: LOG Loading Command: setlang. �
[2020-11-08 00:42:45.506]: LOG Loading Command: setmodlogs. �
[2020-11-08 00:42:45.507]: LOG Loading Command: setprefix. �
[2020-11-08 00:42:45.508]: LOG Loading Command: setreports. �
[2020-11-08 00:42:45.508]: LOG Loading Command: setsuggests. �
[2020-11-08 00:42:45.509]: LOG Loading Command: slowmode. �
[2020-11-08 00:42:45.510]: LOG Loading Command: welcome. �
[2020-11-08 00:42:46.257]: LOG Loading Command: calc. �
[2020-11-08 00:42:46.258]: ERROR Unable to load command fortnite.js: Error: Could not parse font file
[2020-11-08 00:42:46.260]: ERROR Unable to load command fortniteshop.js: Error: Could not parse font file
[2020-11-08 00:42:46.261]: LOG Loading Command: github. �
[2020-11-08 00:42:46.262]: LOG Loading Command: hastebin. �
[2020-11-08 00:42:46.263]: LOG Loading Command: help. �
[2020-11-08 00:42:46.264]: LOG Loading Command: invitations. �
[2020-11-08 00:42:46.265]: LOG Loading Command: invite. �
[2020-11-08 00:42:46.331]: LOG Loading Command: minecraft. �
[2020-11-08 00:42:46.332]: LOG Loading Command: permissions. �
[2020-11-08 00:42:46.332]: LOG Loading Command: ping. �
[2020-11-08 00:42:46.333]: LOG Loading Command: quote. �
[2020-11-08 00:42:46.334]: LOG Loading Command: remindme. �
[2020-11-08 00:42:46.335]: LOG Loading Command: report. �
[2020-11-08 00:42:46.336]: LOG Loading Command: serverinfo. �
[2020-11-08 00:42:46.337]: LOG Loading Command: setafk. �
[2020-11-08 00:42:46.338]: LOG Loading Command: shorturl. �
[2020-11-08 00:42:46.338]: LOG Loading Command: someone. �
[2020-11-08 00:42:46.339]: LOG Loading Command: staff. �
[2020-11-08 00:42:46.340]: LOG Loading Command: stats. �
[2020-11-08 00:42:46.341]: LOG Loading Command: suggest. �
[2020-11-08 00:42:46.345]: LOG Loading Command: translate. �
[2020-11-08 00:42:46.345]: LOG Loading Command: userinfo. �
[2020-11-08 00:42:46.347]: LOG Loading Command: avatar. �
[2020-11-08 00:42:46.348]: LOG Loading Command: captcha. �
[2020-11-08 00:42:46.351]: LOG Loading Command: clyde. �
[2020-11-08 00:42:46.353]: LOG Loading Command: facepalm. �
[2020-11-08 00:42:46.354]: LOG Loading Command: fire. �
[2020-11-08 00:42:46.355]: LOG Loading Command: jail. �
[2020-11-08 00:42:46.356]: LOG Loading Command: love. �
[2020-11-08 00:42:46.357]: LOG Loading Command: mission. �
[2020-11-08 00:42:46.358]: LOG Loading Command: phcomment. �
[2020-11-08 00:42:46.359]: LOG Loading Command: qrcode. �
[2020-11-08 00:42:46.360]: LOG Loading Command: rip. �
[2020-11-08 00:42:46.361]: LOG Loading Command: scary. �
[2020-11-08 00:42:46.361]: LOG Loading Command: tobecontinued. �
[2020-11-08 00:42:46.362]: LOG Loading Command: triggered. �
[2020-11-08 00:42:46.363]: LOG Loading Command: tweet. �
[2020-11-08 00:42:46.364]: LOG Loading Command: wanted. �
[2020-11-08 00:42:46.365]: LOG Loading Command: wasted. �
[2020-11-08 00:42:46.366]: LOG Loading Command: announcement. �
[2020-11-08 00:42:46.367]: LOG Loading Command: ban. �
[2020-11-08 00:42:46.368]: LOG Loading Command: checkinvites. �
[2020-11-08 00:42:46.369]: LOG Loading Command: clear-sanctions. �
[2020-11-08 00:42:46.370]: LOG Loading Command: clear. �
[2020-11-08 00:42:46.371]: LOG Loading Command: giveaway. �
[2020-11-08 00:42:46.371]: LOG Loading Command: kick. �
[2020-11-08 00:42:46.372]: LOG Loading Command: mute. �
[2020-11-08 00:42:46.373]: LOG Loading Command: poll. �
[2020-11-08 00:42:46.374]: LOG Loading Command: sanctions. �
[2020-11-08 00:42:46.375]: LOG Loading Command: setwarns. �
[2020-11-08 00:42:46.375]: LOG Loading Command: unban. �
[2020-11-08 00:42:46.376]: LOG Loading Command: unmute. �
[2020-11-08 00:42:46.377]: LOG Loading Command: warn. �
[2020-11-08 00:42:46.379]: LOG Loading Command: filter. �
[2020-11-08 00:42:46.379]: LOG Loading Command: filters. �
[2020-11-08 00:42:46.530]: LOG Loading Command: lyrics. �
[2020-11-08 00:42:46.531]: LOG Loading Command: np. �
[2020-11-08 00:42:46.532]: LOG Loading Command: pause. �
[2020-11-08 00:42:46.533]: LOG Loading Command: play. �
[2020-11-08 00:42:46.537]: LOG Loading Command: queue. �
[2020-11-08 00:42:46.538]: LOG Loading Command: resume. �
[2020-11-08 00:42:46.538]: LOG Loading Command: skip. �
[2020-11-08 00:42:46.539]: LOG Loading Command: stop. �
[2020-11-08 00:42:46.540]: LOG Loading Command: eval. �
[2020-11-08 00:42:46.541]: LOG Loading Command: reload. �
[2020-11-08 00:42:46.542]: LOG Loading Command: servers-list. �
[2020-11-08 00:42:46.542]: LOG Loading a total of 8 events.
[2020-11-08 00:42:46.542]: LOG Loading Event: guildCreate
[2020-11-08 00:42:46.543]: LOG Loading Event: guildDelete
[2020-11-08 00:42:46.544]: LOG Loading Event: guildMemberAdd
Error: Could not parse font file
    at Object.registerFont (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\node_modules\canvas\index.js:48:17)
    at Object.<anonymous> (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\events\guildMemberAdd.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\atlanta.js:45:22
    at Array.forEach (<anonymous>)
    at init (D:\ЗАГРУЗКИ\Новая папка 3.2\Dev\AtlantaBot\atlanta.js:42:11)

**Comment by Androz2091** [comment]
Install the new version (v4.8.0) and if you still have problems, open a new issue.
