### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by thecyberpop** [Androz2091/AtlantaBot#323]
This is happening everytime I run the work command. 

`This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'name' of null
    at Work.run (/home/container/commands/Economy/work.js:71:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: Cannot read property 'name' of null
    at Work.run (/home/container/commands/Economy/work.js:71:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by Androz2091** [comment]
It shouldn't throw this error if your emojis.json is the same as the one on GitHub. Did you modify it?

**Comment by thecyberpop** [comment]
yes i modified the emojis.json

**Comment by Androz2091** [comment]
Why did you modify it? You should keep it as it is :smile:

**Comment by thecyberpop** [comment]
Thanks :)
