### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by Crni39** [Androz2091/AtlantaBot#355]
```MongooseError: Operation `members.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/container/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:184:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)```

How to conect mongo database?

**Comment by Androz2091** [comment]
Hello, please read the [docs](https://www.atlanta-bot.fr/installation) and if you still have questions please use https://www.atlanta-bot.fr/discord.
