### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by xMeftu** [Androz2091/AtlantaBot#403]
/home/AtlantaBot/node_modules/discord.js/src/client/Client.js:42
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/module.js:11:18)
/home/AtlantaBot/node_modules/discord.js/src/client/Client.js:42
    } catch {
            ^

any solutions?

**Comment by Androz2091** [comment]
You should upgrade Node.js (to v14)
