### ISSUE TITLE
Unexpected token '.' [Before Update it worked correctly (i used repl.it)but now it give me a error] + can i get your discord server link.

### ISSUE THREAD

**Issue by freeh4ckcompany** [Androz2091/AtlantaBot#413]
~/BOT/AtlantaBot$ node .
/home/runner/BOT/AtlantaBot/node_modules/youtube-sr/build/main.js:69
                                    url: item.channel.thumbnails?.default.url,
                                                                 ^

SyntaxError: Unexpected token '.'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/BOT/AtlantaBot/node_modules/discord-player/src/Player.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/BOT/AtlantaBot/node_modules/discord-player/index.js:5:13)

**Comment by freeh4ckcompany** [comment]
in repl.it we can't see node modules folder..

**Comment by sumnermcclure4554554** [comment]
same

**Comment by TuHiN22** [comment]
upgrade your node.js version to 14.x, it will solve the problem

**Comment by TuHiN22** [comment]
> in repl.it we can't see node modules folder..

and sadly repl doesn't support 14.x node version at this moment, so you better have to downgrade discord-player version to work with

**Comment by freeh4ckcompany** [comment]
> > in repl.it we can't see node modules folder..
> 
> and sadly repl doesn't support 14.x node version at this moment, so you better have to downgrade discord-player version to work with

how can i do that please tell me

**Comment by TuHiN22** [comment]
> > > in repl.it we can't see node modules folder..
> > 
> > 
> > and sadly repl doesn't support 14.x node version at this moment, so you better have to downgrade discord-player version to work with
> 
> how can i do that please tell me
on console first type `npm uninstall discord-player` then press enter & after that type `npm i discord-player@3.2.1` then press enter. Done!

**Comment by SickProdigy** [comment]
I think in console you just write `npm install` and it will install or update necessary dependencies.

**Comment by TuHiN22** [comment]
> I think in console from the directory the bot is in, you just write `npm install` and it will install or update necessary dependencies.

nope, only `npm install` won't fix his problem

**Comment by TuHiN22** [comment]
> > > in repl.it we can't see node modules folder..
> > 
> > 
> > and sadly repl doesn't support 14.x node version at this moment, so you better have to downgrade discord-player version to work with
> 
> how can i do that please tell me

on console first type npm uninstall discord-player then press enter & after that type npm i discord-player@3.2.1 then press enter. Done!.

**Comment by freeh4ckcompany** [comment]
I love you bro @TuHiN22 .. really thanks a lot mate .

Actually if you play PUBG PC LITE and want some hacks I am the only developer of that game cheat.. actually there are only 2 cheats / hacks in the world of that game 1 is mine 2 is IDK lol..


But Thanks a lot once again sir.

**Comment by freeh4ckcompany** [comment]
But How can i remove that v.4.9.2 tag in status.., please tell me

**Comment by freeh4ckcompany** [comment]
![Uploading image_2021-03-06_173517.png…]()

**Comment by freeh4ckcompany** [comment]
When i use * invite *invitaion command

[2021-03-06 12:04:40.046]: CMD ! Near (752009162778738780) ran command invite
TypeError: Cannot read property 'me' of undefined
    at Object.supportLink (/home/runner/BOT/AtlantaBot/helpers/functions.js:36:24)
    at Invite.run (/home/runner/BOT/AtlantaBot/commands/General/invite.js:25:83)
    at module.exports.run (/home/runner/BOT/AtlantaBot/events/message.js:236:8)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)



This error

**Comment by Androz2091** [comment]
Open another issue please
