### ISSUE TITLE
Music 

### ISSUE THREAD

**Issue by Emmiez** [Androz2091/AtlantaBot#431]
when I do play I don't hear the music

this is the error im getting

rror: FFmpeg/avconv not found!
    at Function.getInfo (/home/runner/AtlantaBot-6/node_modules/prism-media/src/core/FFmpeg.js:143:11)
    at Function.create (/home/runner/AtlantaBot-6/node_modules/prism-media/src/core/FFmpeg.js:156:38)
    at new FFmpeg (/home/runner/AtlantaBot-6/node_modules/prism-media/src/core/FFmpeg.js:45:27)
    at StreamDownloader (/home/runner/AtlantaBot-6/node_modules/discord-ytdl-core/index.js:45:24)
    at /home/runner/AtlantaBot-6/node_modules/discord-player/src/Player.js:681:31
    at new Promise (<anonymous>)
    at Player._playYTDLStream (/home/runner/AtlantaBot-6/node_modules/discord-player/src/Player.js:667:16)
    at Player._playTrack (/home/runner/AtlantaBot-6/node_modules/discord-player/src/Player.js:747:14)
    at /home/runner/AtlantaBot-6/node_modules/discord-player/src/Player.js:300:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Emmiez** [comment]
I fixed it by doing npm i ffmpeg-static
