### ISSUE TITLE
Please help me fix this error

### ISSUE THREAD

**Issue by Emmiez** [Androz2091/AtlantaBot#433]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/AtlantaBot-6/node_modules/markdown-table/index.js
require() of ES modules is not supported.
require() of /home/runner/AtlantaBot-6/node_modules/markdown-table/index.js from /home/runner/AtlantaBot-6/helpers/autoUpdateDocs.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/AtlantaBot-6/node_modules/markdown-table/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.update (/home/runner/AtlantaBot-6/helpers/autoUpdateDocs.js:10:17)
    at init (/home/runner/AtlantaBot-6/atlanta.cjs:78:17) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by Androz2091** [comment]
It will be fixed soon
