### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ItzMiracleOwO** [Androz2091/AtlantaBot#519]
**Please describe the problem you are having in as much detail as possible:**
Error when execute command play:
```
TypeError: Cannot read property 'play' of undefined
    at Play.run (C:\bot\commands\Music\play.js:38:28)
    at module.exports.run (C:\bot\events\message.js:278:8)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**To Reproduce**
execute command `play`

**Expected behavior**
A clear and concise description of what you expected to happen:
I expect it to start playing music ._.

**Further details:**
- atlanta version: latest
- discord.js version: v12.5.3
- Node.js version: 14.17.3
- Operating system: Windows 10

**Comment by ItzMiracleOwO** [comment]
Fixed
