### ISSUE TITLE
MongoDB connection errors.

### ISSUE THREAD

**Issue by progamer68** [Androz2091/AtlantaBot#523]
Hi, I'm trying to use Atlanta BUT I cannot connect to the mongodb cluster. I get this error:
```
MongooseError: Operation `members.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\progamer68\CloudBot\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:197:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
MongooseError: Operation `users.find()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\progamer68\CloudBot\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:197:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
[2021-07-21 13:36:51.606]: ERROR Unable to connect to the Mongodb database. Error:Error: querySrv ETIMEOUT _mongodb._tcp.cloud.2pzvo.mongodb.net
```

I've setup Mongodb correctly, made sure I used the correct username/password, whitelisted all IP's and made sure I used the right database, but I don't seem to understand whats the problem.

**Comment by le-show-de-didoub74** [comment]
Are you sure you have installed discord.js@12.5.3 ? with the release of the 13.0.0 when you do` npm i discord.js` he install discord.js version 13, so try to do `npm i discord.js@12.5.3`

**Comment by progamer68** [comment]
It is discord.js v12, the latest version. The problem is with the mongodb

**Comment by S1mp1yDucky** [comment]
Update everything
