### ISSUE TITLE
Missing_Scopes

### ISSUE THREAD

**Issue by DonesCute** [Androz2091/AtlantaBot#528]
Having this error/bug, Help command not working everytime I type *help the command gives me this error, 

TypeError [INVITE_MISSING_SCOPES]: At least one valid scope must be provided for the invite
    at Atlanta.generateInvite (C:\Users\Dones\OneDrive\Desktop\ChillAnime\AtlantaBot-master\node_modules\discord.js\src\client\Client.js:457:13)
    at Help.run (C:\Users\Dones\OneDrive\Desktop\ChillAnime\AtlantaBot-master\commands\General\help.js:126:34)
    at module.exports.run (C:\Users\Dones\OneDrive\Desktop\ChillAnime\AtlantaBot-master\events\message.js:236:8)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  [Symbol(code)]: 'INVITE_MISSING_SCOPES'
}

**Comment by 11TStudio** [comment]
Please use the tempalte for the issue.

What node version are you using?
What DiscordJS version ?
What AtlantaBot version?

Is this issue still occurring at the LATEST version of AtlantaBot?

More info please.

**Comment by S1mp1yDucky** [comment]
Same issue here and with a few more errors [https://github.com/Androz2091/AtlantaBot/issues/591](url)
