### ISSUE TITLE
RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number.

### ISSUE THREAD

**Issue by SahrulGnwn** [Androz2091/AtlantaBot#547]
Error when I try to login to my dashboard, how to fix it?

> RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number.
>     at Function.resolve (/root/AtlantaBot/node_modules/discord.js/src/util/BitField.js:150:19)
>     at new BitField (/root/AtlantaBot/node_modules/discord.js/src/util/BitField.js:17:38)
>     at new Permissions (/root/AtlantaBot/node_modules/discord.js/src/util/Permissions.js:11:1)
>     at /root/AtlantaBot/dashboard/utils.js:25:18
>     at Array.forEach (<anonymous>)
>     at Object.fetchUser (/root/AtlantaBot/dashboard/utils.js:24:19)
>     at /root/AtlantaBot/dashboard/app.js:43:64
>     at Layer.handle [as handle_request] (/root/AtlantaBot/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/root/AtlantaBot/node_modules/express/lib/router/index.js:317:13)
>     at /root/AtlantaBot/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/root/AtlantaBot/node_modules/express/lib/router/index.js:335:12)
>     at next (/root/AtlantaBot/node_modules/express/lib/router/index.js:275:10)
>     at Immediate.<anonymous> (/root/AtlantaBot/node_modules/express-session/index.js:506:7)
>     at processImmediate (internal/timers.js:466:21) {
>   bit: 36818497n,
>   [Symbol(code)]: 'BITFIELD_INVALID'
> }

**Comment by 11TStudio** [comment]
> Error when I try to login to my dashboard, how to fix it?

Please use the tempalte for the issue.
What node version are you using?
What DiscordJS version ?
What AtlantaBot version?
Is this issue still occuring at the LATEST version?

More info please.
