### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Mikhail-Simon** [Androz2091/AtlantaBot#568]
**Please describe the problem you are having in as much detail as possible:**

**To Reproduce**
Steps to reproduce the behavior:its loading the command and suddenly stopped at event

**Expected behavior**
A clear and concise description of what you expected to happen:

**Screenshots**
If applicable, add screenshots to help explain your problem:

[2021-09-20 08:38:32.052]: LOG Loading Event: guildCreate 
/home/runner/AtlantaBot/events/guildCreate.js:39
        guildOwner?.send(messageOptions).catch(() => {});
                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/runner/AtlantaBot/atlanta.js:45:22
    at Array.forEach (<anonymous>)
    at init (/home/runner/AtlantaBot/atlanta.js:42:11)

**Further details:**
- atlanta version:4.12.0
- discord.js version:12.5.3
- Node.js version:12.22.4
- Operating system:im running on replit

**Additional context**
Add any other context about the problem here:

**Comment by Mikhail-Simon** [comment]
nvm,remove ? and guildowner
