### ISSUE TITLE
Problème impossible de lancer le bot

### ISSUE THREAD

**Issue by xixi52** [Androz2091/AtlantaBot#6]
J'ai essayé sur plusieurs vps avec des versions de node differente et en local 
discord 11.4-dev n'existe pas 
    "discord.js": "github:discordjs/discord.js#11.4-dev",
package.json 

si j'utilise une autre version de discord.js j'ai cette erreur 
```

/root/xiBot/atlanta.js:26
            new quickdb.table('usersdata'),
            ^

TypeError: quickdb.table is not a constructor
    at new Atlanta (/root/xiBot/atlanta.js:26:13)
    at Object.<anonymous> (/root/xiBot/atlanta.js:72:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

```

Et si node.js est trop récent cette erreur 

```
internal/modules/cjs/loader.js:815
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/root/node_modules/better-sqlite3/build/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/root/node_modules/better-sqlite3/lib/database.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)

```

J'ai essayé de recompiler; de tout réinstaller sachant que j'ai un gros serveur de 1300 personnes qui attendent le retour de leur profil et que le bot était opérationnel jusqu'a ce que je veuille ajouté le site web j'ai besoin d'aide..

PS: je précise que j'ai clone le git sans toucher au code

**Comment by Androz2091** [comment]
Bonjour,
Je viens de mettre à jour la version de discord.js qu'utilise Atlanta, c'est maintenant la 11.5 (dernière release à l'heure actuelle) qui est utilisée. Cela devrait régler le premier problème.

Pour QuickDB, j'ai mis à jour les dependencies du projet vers mon propre fork sur github, ce qui devrait résoudre le problème avec le constructor (donc réinstalle tout).

**Comment by xixi52** [comment]
Fonctionne parfaitement merci beaucoup !!
