### ISSUE TITLE
Dashboard/selector issue

### ISSUE THREAD

**Issue by Peter-MJ-Parker** [Androz2091/AtlantaBot#641]
### Discussed in https://github.com/Androz2091/AtlantaBot/discussions/371

<div type='discussions-op-text'>

<sup>Originally posted by **Shmalle** January  4, 2021</sup>
I wanted to setup the bots dashboard but I got no clue how to continue. I also want to connect a custom domain to is (like https://dashboard.mydomain.xyz)</div>

I have connected my domain successfully, however, the selector isn't working with regards to `user.status`

```
TypeError: /home/marv/bots/AtlantaBot/dashboard/views/selector.ejs:14
    12| 
    13| 			<!-- The sidebar includes the menu -->
 >> 14| 			<%- include('includes/sidebar') %>
    15| 
    16| 			<!-- Content Wrapper. Contains page content -->
    17| 			<div class="content-wrapper">

/home/marv/bots/AtlantaBot/dashboard/views/includes/sidebar.ejs:12
    10|         <div class="pull-left info">
    11|             <p><%= user.username %></p>
 >> 12|             <a href="#"><i class="fa fa-circle text-<%= user.status === 'dnd' ? 'danger' : user.status === 'idle' ? 'warning' : user.status === 'online' ? 'success' : ''%>"></i> <%= translate("common:STATUS_"+user.status.toUpperCase()) %></a>
    13|         </div>
    14|         </div>
    15|         <!-- search form -->

Cannot read properties of undefined (reading 'status')
    at eval ("/home/marv/bots/AtlantaBot/dashboard/views/includes/sidebar.ejs":18:40)
    at sidebar (/home/marv/bots/AtlantaBot/node_modules/ejs/lib/ejs.js:692:17)
    at include (/home/marv/bots/AtlantaBot/node_modules/ejs/lib/ejs.js:690:39)
    at eval ("/home/marv/bots/AtlantaBot/dashboard/views/selector.ejs":18:17)
    at selector (/home/marv/bots/AtlantaBot/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/home/marv/bots/AtlantaBot/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/home/marv/bots/AtlantaBot/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/home/marv/bots/AtlantaBot/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/marv/bots/AtlantaBot/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/marv/bots/AtlantaBot/node_modules/express/lib/application.js:592:3)
```
How can I get the status to pull in?

**Comment by Walimouche** [comment]
Hi, it's been a while, but thanks late for your issue (better late than never xD). Please note that the dashboard will be completely rewritten in AtlantaBot version 6. The current bug has been noted in a (long) notepad, it will be taken into account so that the problem does not reappear in the new dashboard.
